### ISSUE TITLE
El código bajo prueba del TP4 debería tener una función de inicialización

### ISSUE THREAD

**Issue by evolentini** [nhasbun/lse_fiuba_testing_se#6]
Para evitar el problema que se comenta en el readme el código de producción debería incluir una función que descarte todas las sesiones y los datos, la cual debería ser llamada en el `tearDown()` de las pruebas.

**Comment by nhasbun** [comment]
El asunto ahí es que debería hacer uso de funciones que me gustaría probar:

- delete_session y get_session_list debería bastar 

Puedo asumir en estos casos que las funciones hacen lo que deben y ponerme a construir los test ?

**Comment by evolentini** [comment]
Nicolas, desde el punto de vista de nota de los TPs no tiene sentido, pero si lo que quererse es completar las pruebas de la biblioteca para que quede mejor si, podes suponer que funcionan correctamente y usarlas en tearDown, porque en definitiva si no funcionan bien las pruebas no van a pasar correctamente. El único problema de no tener una prueba especifica es que va a ser más difícil encontrar el problema cuando esas funciones sean las que tienen el error.
